In [ ]:
import numpy as np

In [ ]:
# Escribamos nuevamente nuestros elementos y veamos que ocurre con la transposicion.

escalar = 5.6789
vector = np.array([3,4,5,6])
matriz = np.array([[1,2],[3,4],[5,6]])
tensor = np.array([
    [[1,2,3],[4,5,6],[7,8,9]],
    [[11,12,13],[14,15,16],[17,18,19]],
    [[21,22,23],[24,25,26],[27,28,29]],
])

In [ ]:
# La tranposicion para un escalar no tiene sentido, es lo mismo que no hacer nada
# La definicion de la operacion es cambiar filas por columnas, pero un escalar es solo un numero
# escalar = escalar_t como notacion usaremos _t para identificar a los elementos transpuestos
# Como es de esperar si intentamos transponer un escalar nos da error.
escalar.T

AttributeError: 'float' object has no attribute 'T'

In [ ]:
# En cambio matematicamente la transposicion de un vector es cambiar un vector columna en un vector fila
vector_t = vector.T
print(vector.shape)
print(vector)
print(vector_t.shape)
print(vector_t)
# Pero como vemos no tiene implicancia practica en Python ya que nos devuelve el mismo objeto

(4,)
[3 4 5 6]
(4,)
[3 4 5 6]
[ True  True  True  True]


In [ ]:
# Para una matriz vemos el efecto en Python, para que sea mas visual lo hacemos con una matriz de 3x2 y al
# transponer obtenemos una matriz de 2x3, como dijimos antes la operacion es cambiar columnas por filas
matriz_t = matriz.T
print(matriz.shape)
print(matriz)
print(matriz_t.shape)
print(matriz_t)

(3, 2)
[[1 2]
 [3 4]
 [5 6]]
(2, 3)
[[1 3 5]
 [2 4 6]]


In [ ]:
# Que ocurre si transponemos nuevamente una matriz transpuesta?
matriz_t_t = matriz_t.T
print(matriz_t_t.shape)
print(matriz_t_t)
# Obtenemos nuestra matriz original

(3, 2)
[[1 2]
 [3 4]
 [5 6]]


In [ ]:
# Para los tensores la operacion transponer tambien existe, pero es mas complicada ya que es una generalizacion
# de la transposicion de matrices. Por el momento veamos el efecto y que funciona.
tensor_t = tensor.T
print(tensor_t.shape)
print(tensor_t)
print(tensor.shape)
print(tensor)

(3, 3, 3)
[[[ 1 11 21]
  [ 4 14 24]
  [ 7 17 27]]

 [[ 2 12 22]
  [ 5 15 25]
  [ 8 18 28]]

 [[ 3 13 23]
  [ 6 16 26]
  [ 9 19 29]]]
(3, 3, 3)
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]


In [ ]:
# Sumar 2 escalares es directo no tiene sentido que lo veamos, sumar 2 vectores tambien si es que tienen las
# mismas dimensiones, ya veremos que ocurre en Python cuando no tienen las mismas dimensiones
# Ahora veamos como es la suma de 2 matrices que llamaremos A y B con dimension 2x3
A = np.array([[1,2],[3,4],[5,6]])
B = np.array([[6,5],[4,3],[2,1]])
C = A+B
# Que dimension esperas que tenga el resultado C?
print(C.shape)
print(C)

(3, 2)
[[7 7]
 [7 7]
 [7 7]]


In [ ]:
# Resulta que tiene la misma dimension que las matrices sumadas
print(A.shape)
print(B.shape)

(3, 2)
(3, 2)


In [ ]:
# Tambien podemos sumar un escalar a una matriz, esto es sumar el escalar a cada elemento de la matriz
D = A+escalar
print(D.shape)
print(D)

(3, 2)
[[ 6.6789  7.6789]
 [ 8.6789  9.6789]
 [10.6789 11.6789]]


In [ ]:
# Ejercicios
# Calcula la suma de 2 matrices de 5x5, por ejemplo A y A_t
A = np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])
print(A.shape)
# Calcula la suma de 1 matriz y el escalar 11

(5, 5)
