In [ ]:
import numpy as np

In [ ]:
# Ya vimos antes algunos tipos especiales de matrices, para repasar cuales: la identidad, la inversa y las
# singulares

# Ahora es el turno de las matrices diagonales y las simetricas
# En una de las clases anteriores te conte que la matriza diagonal es aquella que tiene valores distintos de cero
# solo en la diagonal, todo el resto de los valores por arriba y abajo son 0

vector = np.array([1,2,3,4,5])
matriz = np.diag(vector)

print(vector)
print(matriz)

[1 2 3 4 5]
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [ ]:
# El anterior es el caso tipico de una matriz cuadrada diagonal, con todos los valores en la diagonal distintos de
# 0, pero tambien tenemos otros casos menos lindos como matrices diagonales no cuadradas

print(matriz[0:4,0:3]) # tambien es una matriz diagonal, solo que no cuadrada

[[1 0 0]
 [0 2 0]
 [0 0 3]
 [0 0 0]]


In [ ]:
# O esta otra matriz tambien es diagonal y no cuadrada

print(matriz[0:3,0:4])

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]]


In [ ]:
# La funcion de numpy np.diag puede ser usada tanto para crear la matriz como hicimos mas arriba como para obtener
# los valores de la diagonal. Cuando crea las matrices las mismas son diagonales cuadradas

print(np.diag(matriz))
print(np.diag(matriz[0:3,0:4]))

[1 2 3 4 5]
[1 2 3]


In [ ]:
# Una propieda importante que tienen las matrices diagonales es que la multiplicacion de un vector por la matriz
# diagonal no es otra cosa que la ponderacion de cada elemento de la diagonal por el vector que multiplica

A = np.diag([2,3,4,5])
print(A)

[[2 0 0 0]
 [0 3 0 0]
 [0 0 4 0]
 [0 0 0 5]]


In [ ]:
v1 = np.array([[1, 1, 1, 1]])
print(v1)
print(A.dot(v1.T))

[[1 1 1 1]]
[[2]
 [3]
 [4]
 [5]]


In [ ]:
# Ahhh pero entonces en el caso de las matrices diagonales cuadradas encontrar su inversa debiera ser simple
# Decimos que debe ser cuadrada porque si no la inversa no existe, pero ademas todos los elementos deben ser
# distintos de 0, ahora veremos porque

# en el punto anterior dijimos que la multiplicacion de una matriz por un vector era la ponderacion de cada
# elemento de la diagonal, ademas ya sabemos que A*A_inv = Identidad (una matriz diagonal cuadrada de unos)

# Por cuanto debo multiplicar al 2 para que me 1? por 1/2 o 0.5, y lo mismo para los otros elementos

A_inv = np.diag([1/2,1/3,1/4,1/5])
print(A_inv)
# Proponemos a A_inv como inversa de A

[[0.5        0.         0.         0.        ]
 [0.         0.33333333 0.         0.        ]
 [0.         0.         0.25       0.        ]
 [0.         0.         0.         0.2       ]]


In [ ]:
# Veamos si A*A_inv nos devuelve la identidad
identidad = A.dot(A_inv)
print(identidad)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# Ya habiamos visto que podiamos usar el comando np.linalg.inv() para calcular la inversa, revisemos que nos da
# lo mismo
A_inv_calc = np.linalg.inv(A)
print(A_inv_calc)
# Efectivamente nos da el mismo resultado

[[0.5        0.         0.         0.        ]
 [0.         0.33333333 0.         0.        ]
 [0.         0.         0.25       0.        ]
 [0.         0.         0.         0.2       ]]


In [ ]:
# Una matriz es simetrica si A = A_t , si una matriz es igual a su transpuesta
# En el caso de una matriz diagonal cuadrada esto es inmediato, no asi si no es cuadrada
print(A.T)
print(A)
# Son iguales

[[2 0 0 0]
 [0 3 0 0]
 [0 0 4 0]
 [0 0 0 5]]
[[2 0 0 0]
 [0 3 0 0]
 [0 0 4 0]
 [0 0 0 5]]


In [ ]:
# Para matrices en general debe ocurrir que los valores estan espejados sobre la diagonal
simetrica = np.array([[1,2,3],[2,-1,7],[3,7,11]])
print(simetrica)
print(simetrica.T)

[[ 1  2  3]
 [ 2 -1  7]
 [ 3  7 11]]
[[ 1  2  3]
 [ 2 -1  7]
 [ 3  7 11]]


In [ ]:
# Recuerdas cuando hablamos de multiplicacion de matrices que vimos (A*B)_t = B_t*A_t
# por el punto anterior si A y B son simetricas entonces A = A_t y B = B_t
# Entonces nos queda que (A*B)_t = B*A y esto es muy importante ya que si nuestras matrices cumplen los
# requisitos, ser simetricas, podemos transponer el producto sin hacer ninguna cuenta, solo cambiando el orden
# en el que multiplicamos, esto tiene implicancias computacionales fuertes

B = np.array([[7,11,13],[11,17,19],[13,19,23]])
print(B)

[[ 7 11 13]
 [11 17 19]
 [13 19 23]]


In [ ]:
# es simetrica
print((simetrica.dot(B).T))
print(B.dot(simetrica))
# Conocer este tipo de propiedades es muy importante para cuando uno esta leyendo lo que alguien mas programo
# o cuando necesitan ahorrar en ciclos de computo, les permite reducir la cantidad de operaciones para llegar
# a un mismo resultado

[[ 68  94 241]
 [102 138 361]
 [120 168 425]]
[[ 68  94 241]
 [102 138 361]
 [120 168 425]]
